// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: stories/stories.proto

package stories

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_IMAGE MediaType = 0
	MediaType_VIDEO MediaType = 1
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "IMAGE",
		1: "VIDEO",
	}
	MediaType_value = map[string]int32{
		"IMAGE": 0,
		"VIDEO": 1,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_stories_stories_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_stories_stories_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{0}
}

type Story struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,3,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	MediaType     MediaType              `protobuf:"varint,4,opt,name=media_type,json=mediaType,proto3,enum=stories.MediaType" json:"media_type,omitempty"`
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"` // in seconds, 5 for images, actual duration for videos
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ViewCount     int32                  `protobuf:"varint,8,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount     int32                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ReplyCount    int32                  `protobuf:"varint,10,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Story) Reset() {
	*x = Story{}
	mi := &file_stories_stories_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Story) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Story) ProtoMessage() {}

func (x *Story) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Story.ProtoReflect.Descriptor instead.
func (*Story) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{0}
}

func (x *Story) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Story) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Story) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *Story) GetMediaType() MediaType {
	if x != nil {
		return x.MediaType
	}
	return MediaType_IMAGE
}

func (x *Story) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Story) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Story) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Story) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Story) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Story) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

type CreateStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,2,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	MediaType     MediaType              `protobuf:"varint,3,opt,name=media_type,json=mediaType,proto3,enum=stories.MediaType" json:"media_type,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoryRequest) Reset() {
	*x = CreateStoryRequest{}
	mi := &file_stories_stories_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoryRequest) ProtoMessage() {}

func (x *CreateStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoryRequest.ProtoReflect.Descriptor instead.
func (*CreateStoryRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateStoryRequest) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *CreateStoryRequest) GetMediaType() MediaType {
	if x != nil {
		return x.MediaType
	}
	return MediaType_IMAGE
}

func (x *CreateStoryRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type CreateStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Story         *Story                 `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoryResponse) Reset() {
	*x = CreateStoryResponse{}
	mi := &file_stories_stories_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoryResponse) ProtoMessage() {}

func (x *CreateStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoryResponse.ProtoReflect.Descriptor instead.
func (*CreateStoryResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStoryResponse) GetStory() *Story {
	if x != nil {
		return x.Story
	}
	return nil
}

type GetStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryRequest) Reset() {
	*x = GetStoryRequest{}
	mi := &file_stories_stories_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryRequest) ProtoMessage() {}

func (x *GetStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryRequest.ProtoReflect.Descriptor instead.
func (*GetStoryRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{3}
}

func (x *GetStoryRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *GetStoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Story         *Story                 `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
	IsLiked       bool                   `protobuf:"varint,2,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	IsViewed      bool                   `protobuf:"varint,3,opt,name=is_viewed,json=isViewed,proto3" json:"is_viewed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryResponse) Reset() {
	*x = GetStoryResponse{}
	mi := &file_stories_stories_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryResponse) ProtoMessage() {}

func (x *GetStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryResponse.ProtoReflect.Descriptor instead.
func (*GetStoryResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{4}
}

func (x *GetStoryResponse) GetStory() *Story {
	if x != nil {
		return x.Story
	}
	return nil
}

func (x *GetStoryResponse) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *GetStoryResponse) GetIsViewed() bool {
	if x != nil {
		return x.IsViewed
	}
	return false
}

type GetUserStoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ViewerId      string                 `protobuf:"bytes,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	IsArchive     bool                   `protobuf:"varint,3,opt,name=is_archive,json=isArchive,proto3" json:"is_archive,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStoriesRequest) Reset() {
	*x = GetUserStoriesRequest{}
	mi := &file_stories_stories_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStoriesRequest) ProtoMessage() {}

func (x *GetUserStoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStoriesRequest.ProtoReflect.Descriptor instead.
func (*GetUserStoriesRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserStoriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserStoriesRequest) GetViewerId() string {
	if x != nil {
		return x.ViewerId
	}
	return ""
}

func (x *GetUserStoriesRequest) GetIsArchive() bool {
	if x != nil {
		return x.IsArchive
	}
	return false
}

func (x *GetUserStoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserStoriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetUserStoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stories       []*Story               `protobuf:"bytes,1,rep,name=stories,proto3" json:"stories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStoriesResponse) Reset() {
	*x = GetUserStoriesResponse{}
	mi := &file_stories_stories_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStoriesResponse) ProtoMessage() {}

func (x *GetUserStoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStoriesResponse.ProtoReflect.Descriptor instead.
func (*GetUserStoriesResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserStoriesResponse) GetStories() []*Story {
	if x != nil {
		return x.Stories
	}
	return nil
}

type GetFollowingStoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingStoriesRequest) Reset() {
	*x = GetFollowingStoriesRequest{}
	mi := &file_stories_stories_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingStoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingStoriesRequest) ProtoMessage() {}

func (x *GetFollowingStoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingStoriesRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingStoriesRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{7}
}

func (x *GetFollowingStoriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFollowingStoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFollowingStoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserStories   []*UserStories         `protobuf:"bytes,1,rep,name=user_stories,json=userStories,proto3" json:"user_stories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingStoriesResponse) Reset() {
	*x = GetFollowingStoriesResponse{}
	mi := &file_stories_stories_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingStoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingStoriesResponse) ProtoMessage() {}

func (x *GetFollowingStoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingStoriesResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingStoriesResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{8}
}

func (x *GetFollowingStoriesResponse) GetUserStories() []*UserStories {
	if x != nil {
		return x.UserStories
	}
	return nil
}

type UserStories struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Stories       []*Story               `protobuf:"bytes,2,rep,name=stories,proto3" json:"stories,omitempty"`
	HasUnseen     bool                   `protobuf:"varint,3,opt,name=has_unseen,json=hasUnseen,proto3" json:"has_unseen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStories) Reset() {
	*x = UserStories{}
	mi := &file_stories_stories_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStories) ProtoMessage() {}

func (x *UserStories) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStories.ProtoReflect.Descriptor instead.
func (*UserStories) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{9}
}

func (x *UserStories) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStories) GetStories() []*Story {
	if x != nil {
		return x.Stories
	}
	return nil
}

func (x *UserStories) GetHasUnseen() bool {
	if x != nil {
		return x.HasUnseen
	}
	return false
}

type DeleteStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStoryRequest) Reset() {
	*x = DeleteStoryRequest{}
	mi := &file_stories_stories_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoryRequest) ProtoMessage() {}

func (x *DeleteStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteStoryRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteStoryRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *DeleteStoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStoryResponse) Reset() {
	*x = DeleteStoryResponse{}
	mi := &file_stories_stories_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoryResponse) ProtoMessage() {}

func (x *DeleteStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteStoryResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteStoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ViewStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewStoryRequest) Reset() {
	*x = ViewStoryRequest{}
	mi := &file_stories_stories_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewStoryRequest) ProtoMessage() {}

func (x *ViewStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewStoryRequest.ProtoReflect.Descriptor instead.
func (*ViewStoryRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{12}
}

func (x *ViewStoryRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *ViewStoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ViewStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewStoryResponse) Reset() {
	*x = ViewStoryResponse{}
	mi := &file_stories_stories_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewStoryResponse) ProtoMessage() {}

func (x *ViewStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewStoryResponse.ProtoReflect.Descriptor instead.
func (*ViewStoryResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{13}
}

func (x *ViewStoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LikeStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeStoryRequest) Reset() {
	*x = LikeStoryRequest{}
	mi := &file_stories_stories_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeStoryRequest) ProtoMessage() {}

func (x *LikeStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeStoryRequest.ProtoReflect.Descriptor instead.
func (*LikeStoryRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{14}
}

func (x *LikeStoryRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *LikeStoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LikeStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeStoryResponse) Reset() {
	*x = LikeStoryResponse{}
	mi := &file_stories_stories_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeStoryResponse) ProtoMessage() {}

func (x *LikeStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeStoryResponse.ProtoReflect.Descriptor instead.
func (*LikeStoryResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{15}
}

func (x *LikeStoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnlikeStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeStoryRequest) Reset() {
	*x = UnlikeStoryRequest{}
	mi := &file_stories_stories_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeStoryRequest) ProtoMessage() {}

func (x *UnlikeStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeStoryRequest.ProtoReflect.Descriptor instead.
func (*UnlikeStoryRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{16}
}

func (x *UnlikeStoryRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *UnlikeStoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UnlikeStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeStoryResponse) Reset() {
	*x = UnlikeStoryResponse{}
	mi := &file_stories_stories_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeStoryResponse) ProtoMessage() {}

func (x *UnlikeStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeStoryResponse.ProtoReflect.Descriptor instead.
func (*UnlikeStoryResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{17}
}

func (x *UnlikeStoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReplyToStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyToStoryRequest) Reset() {
	*x = ReplyToStoryRequest{}
	mi := &file_stories_stories_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyToStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyToStoryRequest) ProtoMessage() {}

func (x *ReplyToStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyToStoryRequest.ProtoReflect.Descriptor instead.
func (*ReplyToStoryRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{18}
}

func (x *ReplyToStoryRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *ReplyToStoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReplyToStoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ReplyToStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         *StoryReply            `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyToStoryResponse) Reset() {
	*x = ReplyToStoryResponse{}
	mi := &file_stories_stories_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyToStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyToStoryResponse) ProtoMessage() {}

func (x *ReplyToStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyToStoryResponse.ProtoReflect.Descriptor instead.
func (*ReplyToStoryResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{19}
}

func (x *ReplyToStoryResponse) GetReply() *StoryReply {
	if x != nil {
		return x.Reply
	}
	return nil
}

type StoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StoryId       string                 `protobuf:"bytes,2,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryReply) Reset() {
	*x = StoryReply{}
	mi := &file_stories_stories_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryReply) ProtoMessage() {}

func (x *StoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryReply.ProtoReflect.Descriptor instead.
func (*StoryReply) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{20}
}

func (x *StoryReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoryReply) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *StoryReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoryReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoryReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetStoryRepliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryRepliesRequest) Reset() {
	*x = GetStoryRepliesRequest{}
	mi := &file_stories_stories_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryRepliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryRepliesRequest) ProtoMessage() {}

func (x *GetStoryRepliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryRepliesRequest.ProtoReflect.Descriptor instead.
func (*GetStoryRepliesRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{21}
}

func (x *GetStoryRepliesRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *GetStoryRepliesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetStoryRepliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*StoryReply          `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryRepliesResponse) Reset() {
	*x = GetStoryRepliesResponse{}
	mi := &file_stories_stories_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryRepliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryRepliesResponse) ProtoMessage() {}

func (x *GetStoryRepliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryRepliesResponse.ProtoReflect.Descriptor instead.
func (*GetStoryRepliesResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{22}
}

func (x *GetStoryRepliesResponse) GetReplies() []*StoryReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

type GetStoryViewersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryViewersRequest) Reset() {
	*x = GetStoryViewersRequest{}
	mi := &file_stories_stories_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryViewersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryViewersRequest) ProtoMessage() {}

func (x *GetStoryViewersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryViewersRequest.ProtoReflect.Descriptor instead.
func (*GetStoryViewersRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{23}
}

func (x *GetStoryViewersRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *GetStoryViewersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetStoryViewersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Viewers       []*StoryViewer         `protobuf:"bytes,1,rep,name=viewers,proto3" json:"viewers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryViewersResponse) Reset() {
	*x = GetStoryViewersResponse{}
	mi := &file_stories_stories_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryViewersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryViewersResponse) ProtoMessage() {}

func (x *GetStoryViewersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryViewersResponse.ProtoReflect.Descriptor instead.
func (*GetStoryViewersResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{24}
}

func (x *GetStoryViewersResponse) GetViewers() []*StoryViewer {
	if x != nil {
		return x.Viewers
	}
	return nil
}

type StoryViewer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ViewedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=viewed_at,json=viewedAt,proto3" json:"viewed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryViewer) Reset() {
	*x = StoryViewer{}
	mi := &file_stories_stories_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryViewer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryViewer) ProtoMessage() {}

func (x *StoryViewer) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryViewer.ProtoReflect.Descriptor instead.
func (*StoryViewer) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{25}
}

func (x *StoryViewer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoryViewer) GetViewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ViewedAt
	}
	return nil
}

type ShareStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecipientId   string                 `protobuf:"bytes,3,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareStoryRequest) Reset() {
	*x = ShareStoryRequest{}
	mi := &file_stories_stories_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareStoryRequest) ProtoMessage() {}

func (x *ShareStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareStoryRequest.ProtoReflect.Descriptor instead.
func (*ShareStoryRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{26}
}

func (x *ShareStoryRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *ShareStoryRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ShareStoryRequest) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

type ShareStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareStoryResponse) Reset() {
	*x = ShareStoryResponse{}
	mi := &file_stories_stories_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareStoryResponse) ProtoMessage() {}

func (x *ShareStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareStoryResponse.ProtoReflect.Descriptor instead.
func (*ShareStoryResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{27}
}

func (x *ShareStoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShareStoryResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GenerateUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUploadURLRequest) Reset() {
	*x = GenerateUploadURLRequest{}
	mi := &file_stories_stories_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadURLRequest) ProtoMessage() {}

func (x *GenerateUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GenerateUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{28}
}

func (x *GenerateUploadURLRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GenerateUploadURLRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type GenerateUploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ObjectName    string                 `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUploadURLResponse) Reset() {
	*x = GenerateUploadURLResponse{}
	mi := &file_stories_stories_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadURLResponse) ProtoMessage() {}

func (x *GenerateUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadURLResponse.ProtoReflect.Descriptor instead.
func (*GenerateUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{29}
}

func (x *GenerateUploadURLResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GenerateUploadURLResponse) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

type ToggleStoryVisibilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleStoryVisibilityRequest) Reset() {
	*x = ToggleStoryVisibilityRequest{}
	mi := &file_stories_stories_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleStoryVisibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleStoryVisibilityRequest) ProtoMessage() {}

func (x *ToggleStoryVisibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleStoryVisibilityRequest.ProtoReflect.Descriptor instead.
func (*ToggleStoryVisibilityRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{30}
}

func (x *ToggleStoryVisibilityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ToggleStoryVisibilityRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type ToggleStoryVisibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsHidden      bool                   `protobuf:"varint,1,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleStoryVisibilityResponse) Reset() {
	*x = ToggleStoryVisibilityResponse{}
	mi := &file_stories_stories_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleStoryVisibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleStoryVisibilityResponse) ProtoMessage() {}

func (x *ToggleStoryVisibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleStoryVisibilityResponse.ProtoReflect.Descriptor instead.
func (*ToggleStoryVisibilityResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{31}
}

func (x *ToggleStoryVisibilityResponse) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

type GetHiddenUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHiddenUsersRequest) Reset() {
	*x = GetHiddenUsersRequest{}
	mi := &file_stories_stories_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHiddenUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHiddenUsersRequest) ProtoMessage() {}

func (x *GetHiddenUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHiddenUsersRequest.ProtoReflect.Descriptor instead.
func (*GetHiddenUsersRequest) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{32}
}

func (x *GetHiddenUsersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetHiddenUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HiddenUserIds []string               `protobuf:"bytes,1,rep,name=hidden_user_ids,json=hiddenUserIds,proto3" json:"hidden_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHiddenUsersResponse) Reset() {
	*x = GetHiddenUsersResponse{}
	mi := &file_stories_stories_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHiddenUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHiddenUsersResponse) ProtoMessage() {}

func (x *GetHiddenUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stories_stories_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHiddenUsersResponse.ProtoReflect.Descriptor instead.
func (*GetHiddenUsersResponse) Descriptor() ([]byte, []int) {
	return file_stories_stories_proto_rawDescGZIP(), []int{33}
}

func (x *GetHiddenUsersResponse) GetHiddenUserIds() []string {
	if x != nil {
		return x.HiddenUserIds
	}
	return nil
}

var File_stories_stories_proto protoreflect.FileDescriptor

const file_stories_stories_proto_rawDesc = "" +
	"\n" +
	"\x15stories/stories.proto\x12\astories\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x02\n" +
	"\x05Story\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmedia_url\x18\x03 \x01(\tR\bmediaUrl\x121\n" +
	"\n" +
	"media_type\x18\x04 \x01(\x0e2\x12.stories.MediaTypeR\tmediaType\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"view_count\x18\b \x01(\x05R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x05R\tlikeCount\x12\x1f\n" +
	"\vreply_count\x18\n" +
	" \x01(\x05R\n" +
	"replyCount\"\x99\x01\n" +
	"\x12CreateStoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmedia_url\x18\x02 \x01(\tR\bmediaUrl\x121\n" +
	"\n" +
	"media_type\x18\x03 \x01(\x0e2\x12.stories.MediaTypeR\tmediaType\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\";\n" +
	"\x13CreateStoryResponse\x12$\n" +
	"\x05story\x18\x01 \x01(\v2\x0e.stories.StoryR\x05story\"E\n" +
	"\x0fGetStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"p\n" +
	"\x10GetStoryResponse\x12$\n" +
	"\x05story\x18\x01 \x01(\v2\x0e.stories.StoryR\x05story\x12\x19\n" +
	"\bis_liked\x18\x02 \x01(\bR\aisLiked\x12\x1b\n" +
	"\tis_viewed\x18\x03 \x01(\bR\bisViewed\"\x9a\x01\n" +
	"\x15GetUserStoriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\tR\bviewerId\x12\x1d\n" +
	"\n" +
	"is_archive\x18\x03 \x01(\bR\tisArchive\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"B\n" +
	"\x16GetUserStoriesResponse\x12(\n" +
	"\astories\x18\x01 \x03(\v2\x0e.stories.StoryR\astories\"K\n" +
	"\x1aGetFollowingStoriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"V\n" +
	"\x1bGetFollowingStoriesResponse\x127\n" +
	"\fuser_stories\x18\x01 \x03(\v2\x14.stories.UserStoriesR\vuserStories\"o\n" +
	"\vUserStories\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\astories\x18\x02 \x03(\v2\x0e.stories.StoryR\astories\x12\x1d\n" +
	"\n" +
	"has_unseen\x18\x03 \x01(\bR\thasUnseen\"H\n" +
	"\x12DeleteStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x13DeleteStoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x10ViewStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"-\n" +
	"\x11ViewStoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x10LikeStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"-\n" +
	"\x11LikeStoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"H\n" +
	"\x12UnlikeStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x13UnlikeStoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"c\n" +
	"\x13ReplyToStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"A\n" +
	"\x14ReplyToStoryResponse\x12)\n" +
	"\x05reply\x18\x01 \x01(\v2\x13.stories.StoryReplyR\x05reply\"\xa5\x01\n" +
	"\n" +
	"StoryReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstory_id\x18\x02 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"L\n" +
	"\x16GetStoryRepliesRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"H\n" +
	"\x17GetStoryRepliesResponse\x12-\n" +
	"\areplies\x18\x01 \x03(\v2\x13.stories.StoryReplyR\areplies\"L\n" +
	"\x16GetStoryViewersRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x17GetStoryViewersResponse\x12.\n" +
	"\aviewers\x18\x01 \x03(\v2\x14.stories.StoryViewerR\aviewers\"_\n" +
	"\vStoryViewer\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x127\n" +
	"\tviewed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bviewedAt\"n\n" +
	"\x11ShareStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12!\n" +
	"\frecipient_id\x18\x03 \x01(\tR\vrecipientId\"M\n" +
	"\x12ShareStoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"T\n" +
	"\x18GenerateUploadURLRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x02 \x01(\tR\bfileType\"[\n" +
	"\x19GenerateUploadURLResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x1f\n" +
	"\vobject_name\x18\x02 \x01(\tR\n" +
	"objectName\"T\n" +
	"\x1cToggleStoryVisibilityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\"<\n" +
	"\x1dToggleStoryVisibilityResponse\x12\x1b\n" +
	"\tis_hidden\x18\x01 \x01(\bR\bisHidden\"0\n" +
	"\x15GetHiddenUsersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x16GetHiddenUsersResponse\x12&\n" +
	"\x0fhidden_user_ids\x18\x01 \x03(\tR\rhiddenUserIds*!\n" +
	"\tMediaType\x12\t\n" +
	"\x05IMAGE\x10\x00\x12\t\n" +
	"\x05VIDEO\x10\x012\xc3\t\n" +
	"\x0eStoriesService\x12H\n" +
	"\vCreateStory\x12\x1b.stories.CreateStoryRequest\x1a\x1c.stories.CreateStoryResponse\x12?\n" +
	"\bGetStory\x12\x18.stories.GetStoryRequest\x1a\x19.stories.GetStoryResponse\x12Q\n" +
	"\x0eGetUserStories\x12\x1e.stories.GetUserStoriesRequest\x1a\x1f.stories.GetUserStoriesResponse\x12`\n" +
	"\x13GetFollowingStories\x12#.stories.GetFollowingStoriesRequest\x1a$.stories.GetFollowingStoriesResponse\x12H\n" +
	"\vDeleteStory\x12\x1b.stories.DeleteStoryRequest\x1a\x1c.stories.DeleteStoryResponse\x12B\n" +
	"\tViewStory\x12\x19.stories.ViewStoryRequest\x1a\x1a.stories.ViewStoryResponse\x12B\n" +
	"\tLikeStory\x12\x19.stories.LikeStoryRequest\x1a\x1a.stories.LikeStoryResponse\x12H\n" +
	"\vUnlikeStory\x12\x1b.stories.UnlikeStoryRequest\x1a\x1c.stories.UnlikeStoryResponse\x12K\n" +
	"\fReplyToStory\x12\x1c.stories.ReplyToStoryRequest\x1a\x1d.stories.ReplyToStoryResponse\x12T\n" +
	"\x0fGetStoryReplies\x12\x1f.stories.GetStoryRepliesRequest\x1a .stories.GetStoryRepliesResponse\x12T\n" +
	"\x0fGetStoryViewers\x12\x1f.stories.GetStoryViewersRequest\x1a .stories.GetStoryViewersResponse\x12E\n" +
	"\n" +
	"ShareStory\x12\x1a.stories.ShareStoryRequest\x1a\x1b.stories.ShareStoryResponse\x12Z\n" +
	"\x11GenerateUploadURL\x12!.stories.GenerateUploadURLRequest\x1a\".stories.GenerateUploadURLResponse\x12f\n" +
	"\x15ToggleStoryVisibility\x12%.stories.ToggleStoryVisibilityRequest\x1a&.stories.ToggleStoryVisibilityResponse\x12Q\n" +
	"\x0eGetHiddenUsers\x12\x1e.stories.GetHiddenUsersRequest\x1a\x1f.stories.GetHiddenUsersResponseB8Z6github.com/Hinsane5/hoshiBmaTchi/backend/proto/storiesb\x06proto3"

var (
	file_stories_stories_proto_rawDescOnce sync.Once
	file_stories_stories_proto_rawDescData []byte
)

func file_stories_stories_proto_rawDescGZIP() []byte {
	file_stories_stories_proto_rawDescOnce.Do(func() {
		file_stories_stories_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stories_stories_proto_rawDesc), len(file_stories_stories_proto_rawDesc)))
	})
	return file_stories_stories_proto_rawDescData
}

var file_stories_stories_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stories_stories_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_stories_stories_proto_goTypes = []any{
	(MediaType)(0),                        // 0: stories.MediaType
	(*Story)(nil),                         // 1: stories.Story
	(*CreateStoryRequest)(nil),            // 2: stories.CreateStoryRequest
	(*CreateStoryResponse)(nil),           // 3: stories.CreateStoryResponse
	(*GetStoryRequest)(nil),               // 4: stories.GetStoryRequest
	(*GetStoryResponse)(nil),              // 5: stories.GetStoryResponse
	(*GetUserStoriesRequest)(nil),         // 6: stories.GetUserStoriesRequest
	(*GetUserStoriesResponse)(nil),        // 7: stories.GetUserStoriesResponse
	(*GetFollowingStoriesRequest)(nil),    // 8: stories.GetFollowingStoriesRequest
	(*GetFollowingStoriesResponse)(nil),   // 9: stories.GetFollowingStoriesResponse
	(*UserStories)(nil),                   // 10: stories.UserStories
	(*DeleteStoryRequest)(nil),            // 11: stories.DeleteStoryRequest
	(*DeleteStoryResponse)(nil),           // 12: stories.DeleteStoryResponse
	(*ViewStoryRequest)(nil),              // 13: stories.ViewStoryRequest
	(*ViewStoryResponse)(nil),             // 14: stories.ViewStoryResponse
	(*LikeStoryRequest)(nil),              // 15: stories.LikeStoryRequest
	(*LikeStoryResponse)(nil),             // 16: stories.LikeStoryResponse
	(*UnlikeStoryRequest)(nil),            // 17: stories.UnlikeStoryRequest
	(*UnlikeStoryResponse)(nil),           // 18: stories.UnlikeStoryResponse
	(*ReplyToStoryRequest)(nil),           // 19: stories.ReplyToStoryRequest
	(*ReplyToStoryResponse)(nil),          // 20: stories.ReplyToStoryResponse
	(*StoryReply)(nil),                    // 21: stories.StoryReply
	(*GetStoryRepliesRequest)(nil),        // 22: stories.GetStoryRepliesRequest
	(*GetStoryRepliesResponse)(nil),       // 23: stories.GetStoryRepliesResponse
	(*GetStoryViewersRequest)(nil),        // 24: stories.GetStoryViewersRequest
	(*GetStoryViewersResponse)(nil),       // 25: stories.GetStoryViewersResponse
	(*StoryViewer)(nil),                   // 26: stories.StoryViewer
	(*ShareStoryRequest)(nil),             // 27: stories.ShareStoryRequest
	(*ShareStoryResponse)(nil),            // 28: stories.ShareStoryResponse
	(*GenerateUploadURLRequest)(nil),      // 29: stories.GenerateUploadURLRequest
	(*GenerateUploadURLResponse)(nil),     // 30: stories.GenerateUploadURLResponse
	(*ToggleStoryVisibilityRequest)(nil),  // 31: stories.ToggleStoryVisibilityRequest
	(*ToggleStoryVisibilityResponse)(nil), // 32: stories.ToggleStoryVisibilityResponse
	(*GetHiddenUsersRequest)(nil),         // 33: stories.GetHiddenUsersRequest
	(*GetHiddenUsersResponse)(nil),        // 34: stories.GetHiddenUsersResponse
	(*timestamppb.Timestamp)(nil),         // 35: google.protobuf.Timestamp
}
var file_stories_stories_proto_depIdxs = []int32{
	0,  // 0: stories.Story.media_type:type_name -> stories.MediaType
	35, // 1: stories.Story.created_at:type_name -> google.protobuf.Timestamp
	35, // 2: stories.Story.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 3: stories.CreateStoryRequest.media_type:type_name -> stories.MediaType
	1,  // 4: stories.CreateStoryResponse.story:type_name -> stories.Story
	1,  // 5: stories.GetStoryResponse.story:type_name -> stories.Story
	1,  // 6: stories.GetUserStoriesResponse.stories:type_name -> stories.Story
	10, // 7: stories.GetFollowingStoriesResponse.user_stories:type_name -> stories.UserStories
	1,  // 8: stories.UserStories.stories:type_name -> stories.Story
	21, // 9: stories.ReplyToStoryResponse.reply:type_name -> stories.StoryReply
	35, // 10: stories.StoryReply.created_at:type_name -> google.protobuf.Timestamp
	21, // 11: stories.GetStoryRepliesResponse.replies:type_name -> stories.StoryReply
	26, // 12: stories.GetStoryViewersResponse.viewers:type_name -> stories.StoryViewer
	35, // 13: stories.StoryViewer.viewed_at:type_name -> google.protobuf.Timestamp
	2,  // 14: stories.StoriesService.CreateStory:input_type -> stories.CreateStoryRequest
	4,  // 15: stories.StoriesService.GetStory:input_type -> stories.GetStoryRequest
	6,  // 16: stories.StoriesService.GetUserStories:input_type -> stories.GetUserStoriesRequest
	8,  // 17: stories.StoriesService.GetFollowingStories:input_type -> stories.GetFollowingStoriesRequest
	11, // 18: stories.StoriesService.DeleteStory:input_type -> stories.DeleteStoryRequest
	13, // 19: stories.StoriesService.ViewStory:input_type -> stories.ViewStoryRequest
	15, // 20: stories.StoriesService.LikeStory:input_type -> stories.LikeStoryRequest
	17, // 21: stories.StoriesService.UnlikeStory:input_type -> stories.UnlikeStoryRequest
	19, // 22: stories.StoriesService.ReplyToStory:input_type -> stories.ReplyToStoryRequest
	22, // 23: stories.StoriesService.GetStoryReplies:input_type -> stories.GetStoryRepliesRequest
	24, // 24: stories.StoriesService.GetStoryViewers:input_type -> stories.GetStoryViewersRequest
	27, // 25: stories.StoriesService.ShareStory:input_type -> stories.ShareStoryRequest
	29, // 26: stories.StoriesService.GenerateUploadURL:input_type -> stories.GenerateUploadURLRequest
	31, // 27: stories.StoriesService.ToggleStoryVisibility:input_type -> stories.ToggleStoryVisibilityRequest
	33, // 28: stories.StoriesService.GetHiddenUsers:input_type -> stories.GetHiddenUsersRequest
	3,  // 29: stories.StoriesService.CreateStory:output_type -> stories.CreateStoryResponse
	5,  // 30: stories.StoriesService.GetStory:output_type -> stories.GetStoryResponse
	7,  // 31: stories.StoriesService.GetUserStories:output_type -> stories.GetUserStoriesResponse
	9,  // 32: stories.StoriesService.GetFollowingStories:output_type -> stories.GetFollowingStoriesResponse
	12, // 33: stories.StoriesService.DeleteStory:output_type -> stories.DeleteStoryResponse
	14, // 34: stories.StoriesService.ViewStory:output_type -> stories.ViewStoryResponse
	16, // 35: stories.StoriesService.LikeStory:output_type -> stories.LikeStoryResponse
	18, // 36: stories.StoriesService.UnlikeStory:output_type -> stories.UnlikeStoryResponse
	20, // 37: stories.StoriesService.ReplyToStory:output_type -> stories.ReplyToStoryResponse
	23, // 38: stories.StoriesService.GetStoryReplies:output_type -> stories.GetStoryRepliesResponse
	25, // 39: stories.StoriesService.GetStoryViewers:output_type -> stories.GetStoryViewersResponse
	28, // 40: stories.StoriesService.ShareStory:output_type -> stories.ShareStoryResponse
	30, // 41: stories.StoriesService.GenerateUploadURL:output_type -> stories.GenerateUploadURLResponse
	32, // 42: stories.StoriesService.ToggleStoryVisibility:output_type -> stories.ToggleStoryVisibilityResponse
	34, // 43: stories.StoriesService.GetHiddenUsers:output_type -> stories.GetHiddenUsersResponse
	29, // [29:44] is the sub-list for method output_type
	14, // [14:29] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_stories_stories_proto_init() }
func file_stories_stories_proto_init() {
	if File_stories_stories_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stories_stories_proto_rawDesc), len(file_stories_stories_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stories_stories_proto_goTypes,
		DependencyIndexes: file_stories_stories_proto_depIdxs,
		EnumInfos:         file_stories_stories_proto_enumTypes,
		MessageInfos:      file_stories_stories_proto_msgTypes,
	}.Build()
	File_stories_stories_proto = out.File
	file_stories_stories_proto_goTypes = nil
	file_stories_stories_proto_depIdxs = nil
}
