// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: users/users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOtpRequest) Reset() {
	*x = SendOtpRequest{}
	mi := &file_users_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpRequest) ProtoMessage() {}

func (x *SendOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpRequest.ProtoReflect.Descriptor instead.
func (*SendOtpRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{0}
}

func (x *SendOtpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendOtpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOtpResponse) Reset() {
	*x = SendOtpResponse{}
	mi := &file_users_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpResponse) ProtoMessage() {}

func (x *SendOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpResponse.ProtoReflect.Descriptor instead.
func (*SendOtpResponse) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{1}
}

func (x *SendOtpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterUserRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username              string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                 string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password              string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	DateOfBirth           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date_of_birth,proto3" json:"date_of_birth,omitempty"`
	Gender                string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	ProfilePictureUrl     string                 `protobuf:"bytes,7,opt,name=profile_picture_url,proto3" json:"profile_picture_url,omitempty"`
	ConfirmPassword       string                 `protobuf:"bytes,8,opt,name=confirm_password,proto3" json:"confirm_password,omitempty"`
	SubscribeToNewsletter bool                   `protobuf:"varint,9,opt,name=subscribe_to_newsletter,proto3" json:"subscribe_to_newsletter,omitempty"`
	Enable_2Fa            bool                   `protobuf:"varint,10,opt,name=enable_2fa,proto3" json:"enable_2fa,omitempty"`
	OtpCode               string                 `protobuf:"bytes,11,opt,name=otp_code,proto3" json:"otp_code,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_users_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *RegisterUserRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *RegisterUserRequest) GetProfilePictureUrl() string {
	if x != nil {
		return x.ProfilePictureUrl
	}
	return ""
}

func (x *RegisterUserRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

func (x *RegisterUserRequest) GetSubscribeToNewsletter() bool {
	if x != nil {
		return x.SubscribeToNewsletter
	}
	return false
}

func (x *RegisterUserRequest) GetEnable_2Fa() bool {
	if x != nil {
		return x.Enable_2Fa
	}
	return false
}

func (x *RegisterUserRequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

type RegisterUserResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username          string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email             string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	DateOfBirth       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date_of_birth,proto3" json:"date_of_birth,omitempty"`
	Gender            string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	ProfilePictureUrl string                 `protobuf:"bytes,7,opt,name=profile_picture_url,proto3" json:"profile_picture_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_users_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserResponse) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *RegisterUserResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *RegisterUserResponse) GetProfilePictureUrl() string {
	if x != nil {
		return x.ProfilePictureUrl
	}
	return ""
}

var File_users_users_proto protoreflect.FileDescriptor

const file_users_users_proto_rawDesc = "" +
	"\n" +
	"\x11users/users.proto\x12\x05users\x1a\x1fgoogle/protobuf/timestamp.proto\"&\n" +
	"\x0eSendOtpRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"+\n" +
	"\x0fSendOtpResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa5\x03\n" +
	"\x13RegisterUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12@\n" +
	"\rdate_of_birth\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rdate_of_birth\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x120\n" +
	"\x13profile_picture_url\x18\a \x01(\tR\x13profile_picture_url\x12*\n" +
	"\x10confirm_password\x18\b \x01(\tR\x10confirm_password\x128\n" +
	"\x17subscribe_to_newsletter\x18\t \x01(\bR\x17subscribe_to_newsletter\x12\x1e\n" +
	"\n" +
	"enable_2fa\x18\n" +
	" \x01(\bR\n" +
	"enable_2fa\x12\x1a\n" +
	"\botp_code\x18\v \x01(\tR\botp_code\"\x82\x02\n" +
	"\x14RegisterUserResponse\x12\x18\n" +
	"\auser_id\x18\x01 \x01(\tR\auser_id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12@\n" +
	"\rdate_of_birth\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rdate_of_birth\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x120\n" +
	"\x13profile_picture_url\x18\a \x01(\tR\x13profile_picture_url2\x90\x01\n" +
	"\vUserService\x12G\n" +
	"\fRegisterUser\x12\x1a.users.RegisterUserRequest\x1a\x1b.users.RegisterUserResponse\x128\n" +
	"\aSendOtp\x12\x15.users.SendOtpRequest\x1a\x16.users.SendOtpResponseB6Z4github.com/Hinsane5/hoshiBmaTchi/backend/proto/usersb\x06proto3"

var (
	file_users_users_proto_rawDescOnce sync.Once
	file_users_users_proto_rawDescData []byte
)

func file_users_users_proto_rawDescGZIP() []byte {
	file_users_users_proto_rawDescOnce.Do(func() {
		file_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_users_proto_rawDesc), len(file_users_users_proto_rawDesc)))
	})
	return file_users_users_proto_rawDescData
}

var file_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_users_users_proto_goTypes = []any{
	(*SendOtpRequest)(nil),        // 0: users.SendOtpRequest
	(*SendOtpResponse)(nil),       // 1: users.SendOtpResponse
	(*RegisterUserRequest)(nil),   // 2: users.RegisterUserRequest
	(*RegisterUserResponse)(nil),  // 3: users.RegisterUserResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_users_users_proto_depIdxs = []int32{
	4, // 0: users.RegisterUserRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	4, // 1: users.RegisterUserResponse.date_of_birth:type_name -> google.protobuf.Timestamp
	2, // 2: users.UserService.RegisterUser:input_type -> users.RegisterUserRequest
	0, // 3: users.UserService.SendOtp:input_type -> users.SendOtpRequest
	3, // 4: users.UserService.RegisterUser:output_type -> users.RegisterUserResponse
	1, // 5: users.UserService.SendOtp:output_type -> users.SendOtpResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_users_users_proto_init() }
func file_users_users_proto_init() {
	if File_users_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_users_proto_rawDesc), len(file_users_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_users_proto_goTypes,
		DependencyIndexes: file_users_users_proto_depIdxs,
		MessageInfos:      file_users_users_proto_msgTypes,
	}.Build()
	File_users_users_proto = out.File
	file_users_users_proto_goTypes = nil
	file_users_users_proto_depIdxs = nil
}
